package view.GUI.ROOMS;

import controller.BookingResource;
import view.GUI.Main_GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Rooms extends JFrame {
    private JButton ADDROOMButton;
    private JPanel rooms;
    private JButton DELETEROOMSButton;
    private JButton VIEWROOMSButton;
    private JButton BACKButton;

    public Rooms(BookingResource bookingResource) {
        setContentPane(this.rooms);
        setTitle("ESCAPE THEMES");
        setSize(450, 450);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        BACKButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Main_GUI(bookingResource);
            }
        });
        ADDROOMButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new AddRoom(bookingResource);
            }
        });
        DELETEROOMSButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new DelRoom(bookingResource);
            }
        });
        VIEWROOMSButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new ViewRooms(bookingResource);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rooms = new JPanel();
        rooms.setLayout(new GridBagLayout());
        ADDROOMButton = new JButton();
        ADDROOMButton.setText("ADD THEME");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        rooms.add(ADDROOMButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        rooms.add(spacer1, gbc);
        DELETEROOMSButton = new JButton();
        DELETEROOMSButton.setText("DELETE THEME");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        rooms.add(DELETEROOMSButton, gbc);
        VIEWROOMSButton = new JButton();
        VIEWROOMSButton.setText("VIEW THEMES");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        rooms.add(VIEWROOMSButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("ESCAPE THEMES");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        rooms.add(label1, gbc);
        BACKButton = new JButton();
        BACKButton.setText("BACK");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        rooms.add(BACKButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rooms;
    }

}
