package view.GUI.USER;

import controller.BookingResource;
import model.User.User;
import view.GUI.Main_GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;

public class ViewUser extends JFrame {
    private JPanel viewUser;
    private JButton mainMenuButton;
    private JTextArea textArea1;
    private JButton SHOWALLUSERSButton;

    public ViewUser(BookingResource bookingResource) {
        setContentPane(this.viewUser);
        setTitle("VIEW ALL CUSTOMERS");
        setSize(450, 450);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);

        SHOWALLUSERSButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    Map<String, User> viewUsers = bookingResource.viewUsers();
                    for (Map.Entry<String, User> entry : viewUsers.entrySet()) {
                        Object value = entry.getValue();
                        JOptionPane.showMessageDialog(viewUser, value + "\n");
                    }
                } catch (IllegalArgumentException ex) {
                    String error = ex.getLocalizedMessage();
                    JOptionPane.showMessageDialog(viewUser, error);
                }
            }
        });
        mainMenuButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Main_GUI(bookingResource);
            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        viewUser = new JPanel();
        viewUser.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        viewUser.add(label1, gbc);
        textArea1 = new JTextArea();
        textArea1.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        viewUser.add(textArea1, gbc);
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(0);
        label2.setHorizontalTextPosition(0);
        label2.setText("VIEW ALL CUSTOMERS");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        viewUser.add(label2, gbc);
        mainMenuButton = new JButton();
        mainMenuButton.setText("Main Menu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        viewUser.add(mainMenuButton, gbc);
        SHOWALLUSERSButton = new JButton();
        SHOWALLUSERSButton.setText("SHOW ALL CUSTOMERS");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        viewUser.add(SHOWALLUSERSButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return viewUser;
    }

}
