package view.GUI.Reservation;

import controller.BookingResource;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;

public class AddReservation extends JFrame {
    private JPanel addReservation;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JTextField textField5;
    private JTextField textField6;
    private JTextField textField7;
    private JTextField textField8;
    private JButton okButton;
    private JButton backButton;

    public AddReservation(BookingResource bookingResource) {
        setContentPane(this.addReservation);
        setTitle("RESERVATION");
        setSize(600, 600);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        backButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Reservation(bookingResource);
            }
        });
        okButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                String bookingID = textField1.getText();
                String emailID = textField2.getText();
                String buildingName = textField3.getText();
                String roomName = textField4.getText();
                String checkInDate = textField5.getText();
                String checkOutDate = textField6.getText();
                String checkInTime = textField7.getText();
                String checkOutTime = textField8.getText();
                try {
                    bookingResource.checkID(bookingID);
                    bookingResource.checkUser(emailID);
                    bookingResource.checkBuilding(buildingName);
                    bookingResource.checkRoom(roomName); // To check if a Room exists or not.
                    bookingResource.isDateValid(checkInDate);
                    bookingResource.isDateValid(checkOutDate);
                    bookingResource.validateTime(checkInTime);
                    bookingResource.validateTime(checkOutTime);
                    bookingResource.isBeforeTime(checkInTime, checkOutTime);
                    bookingResource.LeastBy5(checkInTime, checkOutTime);
                    bookingResource.checkDay(checkInDate, checkOutDate);
                    bookingResource.checkOverlap(checkInTime, checkOutTime, roomName, checkInDate);
                    boolean isBooked = true;
                    bookingResource.updateRoom(roomName, buildingName, isBooked);
                    bookingResource.addReservation(bookingID, emailID, buildingName, roomName, checkInDate, checkOutDate, checkInTime, checkOutTime, isBooked);
                    JOptionPane.showMessageDialog(addReservation, "Reservation Completed Successfully.");
                } catch (IllegalArgumentException ex) {
                    String error = ex.getLocalizedMessage();
                    JOptionPane.showMessageDialog(addReservation, error);
                } catch (ParseException ex) {
                    String error = ex.getLocalizedMessage();
                    JOptionPane.showMessageDialog(addReservation, error);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        addReservation = new JPanel();
        addReservation.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("ADD A RESERVATION");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        addReservation.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(spacer1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("BOOKING ID(REFERNCE)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        addReservation.add(label2, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(textField1, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("EMAIL");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        addReservation.add(label3, gbc);
        textField2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(textField2, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("CAFE BRANCH NAME");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        addReservation.add(label4, gbc);
        textField3 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(textField3, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("THEME NAME");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        addReservation.add(label5, gbc);
        textField4 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(textField4, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Enter BOOK-IN Date dd/mm/yyyy example 02/12/2022");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        addReservation.add(label6, gbc);
        textField5 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(textField5, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Enter BOOK-OUT Date dd/mm/yyyy example 02/12/2022");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.anchor = GridBagConstraints.WEST;
        addReservation.add(label7, gbc);
        textField6 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(textField6, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Enter the IN Time HH:mm in 24-hr format");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        addReservation.add(label8, gbc);
        textField7 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 14;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(textField7, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Enter the OUT Time HH:mm in 24-hr format");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 15;
        gbc.anchor = GridBagConstraints.WEST;
        addReservation.add(label9, gbc);
        textField8 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 16;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(textField8, gbc);
        okButton = new JButton();
        okButton.setText("Ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(okButton, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addReservation.add(backButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return addReservation;
    }

}
