package view.GUI.Reservation;

import controller.BookingResource;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DelReservation extends JFrame {
    private JTextField textField1;
    private JButton okButton;
    private JButton backButton;
    private JPanel delReservation;

    public DelReservation(BookingResource bookingResource) {
        setContentPane(this.delReservation);
        setTitle("예약 취소");
        setSize(450, 450);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        okButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                String bookingID = textField1.getText();
                if (bookingID.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(delReservation, "예약 번호를 입력해 주세요.");
                } else {
                    try {
                        bookingResource.cancelReservation(bookingID);
                        JOptionPane.showMessageDialog(delReservation, "예약이 취소되었습니다.");
                    } catch (IllegalArgumentException ex) {
                        String error = ex.getLocalizedMessage();
                        JOptionPane.showMessageDialog(delReservation, error);
                    }
                }
            }
        });
        backButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Reservation(bookingResource);
            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        delReservation = new JPanel();
        delReservation.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("예약 취소");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        delReservation.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delReservation.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        delReservation.add(spacer2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("예약 번호");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        delReservation.add(label2, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delReservation.add(textField1, gbc);
        okButton = new JButton();
        okButton.setText("확인");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delReservation.add(okButton, gbc);
        backButton = new JButton();
        backButton.setText("뒤로");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delReservation.add(backButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return delReservation;
    }

}
