package view.GUI.Reservation;

import controller.BookingResource;
import view.GUI.Main_GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Reservation extends JFrame {
    private JButton BOOKAROOMButton;
    private JButton DELETEABOOKINGButton;
    private JButton MAINMENUButton;
    private JButton ADDPLAYRESULTButton;
    private JButton VIEWPLAYRESULTSButton;
    private JPanel reservation;

    public Reservation(BookingResource bookingResource) {
        setContentPane(this.reservation);
        setTitle("Escape Room Manager - Reservations");
        setSize(540, 420);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        MAINMENUButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Main_GUI(bookingResource);
            }
        });
        BOOKAROOMButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new AddReservation(bookingResource);
            }
        });
        DELETEABOOKINGButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new DelReservation(bookingResource);
            }
        });
        ADDPLAYRESULTButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new AddPlayResult(bookingResource);
            }
        });
        VIEWPLAYRESULTSButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new ViewPlayResults(bookingResource);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        reservation = new JPanel();
        reservation.setLayout(new GridBagLayout());
        BOOKAROOMButton = new JButton();
        BOOKAROOMButton.setText("1. Book Escape Theme");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        reservation.add(BOOKAROOMButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        reservation.add(spacer1, gbc);
        DELETEABOOKINGButton = new JButton();
        DELETEABOOKINGButton.setText("2. Delete Reservation");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        reservation.add(DELETEABOOKINGButton, gbc);
        MAINMENUButton = new JButton();
        MAINMENUButton.setText("Back to Main Menu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        reservation.add(MAINMENUButton, gbc);
        ADDPLAYRESULTButton = new JButton();
        ADDPLAYRESULTButton.setText("3. Add Play Result");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        reservation.add(ADDPLAYRESULTButton, gbc);
        VIEWPLAYRESULTSButton = new JButton();
        VIEWPLAYRESULTSButton.setText("4. View Play Results");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        reservation.add(VIEWPLAYRESULTSButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, 18));
        label1.setText("Reservation & Play Result Management");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        reservation.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return reservation;
    }

}
