package view.GUI.Reservation;

import controller.BookingResource;
import model.Reservation.Reservation;
import view.GUI.Main_GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;

public class ReservationBID extends JFrame {
    private JPanel resEmailID;
    private JTextField textField1;
    private JButton OKButton;
    private JButton backButton;

    public ReservationBID(BookingResource bookingResource) {
        setContentPane(this.resEmailID);
        setTitle("예약 번호로 예약 조회");
        setSize(450, 450);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);

        OKButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                String bookingID = textField1.getText().trim();
                Map<String, Reservation> viewBookingIDRes = new HashMap<>();
                try {
                    if (bookingID.isEmpty()) {
                        throw new IllegalArgumentException("입력 항목을 작성해 주세요.");
                    }
                    viewBookingIDRes = bookingResource.viewMyRes(bookingID);
                    for (Map.Entry<String, Reservation> entry : viewBookingIDRes.entrySet()) {
                        String key = entry.getKey();
                        Object value = entry.getValue();
                        JOptionPane.showMessageDialog(resEmailID, "예약 번호: " + entry.getValue().getBookingID() + "\n고객 이메일: " + entry.getValue().getEmail() + "\n지점명: " + entry.getValue().getBuildingName() + "\n테마명: " + entry.getValue().getRoom() + "\n시작 시간: " + entry.getValue().getCheckInDate() + ":" + entry.getValue().getCheckInTime() + "\n종료 시간: " + entry.getValue().getCheckOutDate() + ":" + entry.getValue().getCheckOutTime() + "\n예약 인원: " + entry.getValue().getPlayerCount() + "명\n총 가격: " + entry.getValue().getTotalPrice() + "원\n예약 상태: " + entry.getValue().getStatusDisplayName() + "\n");
                    }
                } catch (IllegalArgumentException ex) {
                    String error = ex.getLocalizedMessage();
                    JOptionPane.showMessageDialog(resEmailID, error);
                }
            }

        });
        backButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Main_GUI(bookingResource);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        resEmailID = new JPanel();
        resEmailID.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("예약 번호로 예약 조회");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        resEmailID.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("예약 번호");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        resEmailID.add(label2, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        resEmailID.add(textField1, gbc);
        OKButton = new JButton();
        OKButton.setText("확인");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        resEmailID.add(OKButton, gbc);
        backButton = new JButton();
        backButton.setText("뒤로");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        resEmailID.add(backButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return resEmailID;
    }

}
