package view.GUI.BUILDINGS;

import controller.BookingResource;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddBuildings extends JFrame {
    private JPanel addBuildings;
    private JButton backButton;
    private JTextField textField1;
    private JTextField textField2;
    private JButton okButton;
    private JTextField textField3;

    public AddBuildings(BookingResource bookingResource) {
        setContentPane(this.addBuildings);
        setTitle("ADD CAFE BRANCH");
        setSize(450, 450);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        backButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Buildings(bookingResource);
            }
        });
        okButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                String emailID = textField3.getText().trim();
                String buildingName = textField1.getText().trim();
                String address = textField2.getText().trim();
                try {
                    if (emailID.trim().isEmpty() || buildingName.trim().isEmpty() || address.trim().isEmpty()) {
                        throw new IllegalArgumentException("Text Fields are Empty");
                    }
                    bookingResource.checkUser(emailID);
                    bookingResource.addBuilding(buildingName, address, emailID);
                    JOptionPane.showMessageDialog(addBuildings, "Building Added Sucessfully.");
                } catch (IllegalArgumentException ex) {
                    String error = ex.getLocalizedMessage();
                    JOptionPane.showMessageDialog(addBuildings, error);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        addBuildings = new JPanel();
        addBuildings.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("ADD CAFE BRANCH");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        addBuildings.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addBuildings.add(spacer1, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addBuildings.add(backButton, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Enter Cafe Branch Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        addBuildings.add(label2, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addBuildings.add(textField1, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Enter Address");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        addBuildings.add(label3, gbc);
        textField2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addBuildings.add(textField2, gbc);
        okButton = new JButton();
        okButton.setText("Ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addBuildings.add(okButton, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Enter Email-ID");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        addBuildings.add(label4, gbc);
        textField3 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addBuildings.add(textField3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return addBuildings;
    }

}
