package view.GUI.BUILDINGS;

import controller.BookingResource;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DelBuilding extends JFrame {
    private JTextField textField1;
    private JTextField textField2;
    private JButton okButton;
    private JButton backButton;
    private JPanel delBuilding;

    public DelBuilding(BookingResource bookingResource) {
        setContentPane(this.delBuilding);
        setTitle("DELETE CAFE BRANCH");
        setSize(450, 450);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        backButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Buildings(bookingResource);
            }
        });
        okButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                String emailID = textField1.getText().trim();
                String buildingName = textField2.getText().trim();
                try {
                    if (emailID.isEmpty() || buildingName.isEmpty()) {
                        throw new IllegalArgumentException("Text Fields cannot be empty.");
                    }
                    bookingResource.checkUser(emailID);
                    bookingResource.delRoomFromBuild(buildingName);
                    bookingResource.delBuilding(buildingName);
                    JOptionPane.showMessageDialog(delBuilding, "Building Deleted Successfully");
                } catch (IllegalArgumentException ex) {
                    String error = ex.getLocalizedMessage();
                    JOptionPane.showMessageDialog(delBuilding, error);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        delBuilding = new JPanel();
        delBuilding.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("DELETE CAFE BRANCH");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        delBuilding.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delBuilding.add(spacer1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("CUSTOMER EMAIL");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        delBuilding.add(label2, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delBuilding.add(textField1, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("CAFE BRANCH NAME");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        delBuilding.add(label3, gbc);
        textField2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delBuilding.add(textField2, gbc);
        okButton = new JButton();
        okButton.setText("Ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delBuilding.add(okButton, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        delBuilding.add(backButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return delBuilding;
    }

}
