package view.GUI.BUILDINGS;

import controller.BookingResource;
import model.Building.Building;
import view.GUI.Main_GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;

public class ViewBuilding extends JFrame {
    private JButton BACKButton;
    private JButton SHOWBUILDINGSButton;
    private JPanel viewBuildings;

    public ViewBuilding(BookingResource bookingResource) {
        setContentPane(this.viewBuildings);
        setTitle("전체 지점 조회");
        setSize(450, 450);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        BACKButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new Main_GUI(bookingResource);
            }
        });
        SHOWBUILDINGSButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    Map<String, Building> buildings = bookingResource.viewBuildings();
                    for (Map.Entry<String, Building> entry : buildings.entrySet()) {
                        String key = entry.getKey();
                        Object value = entry.getValue().getBuildingName();
                        Object address = entry.getValue().getAddress();
                        JOptionPane.showMessageDialog(viewBuildings, "지점명: " + value + "\n주소: " + address + "\n");
                    }
                } catch (IllegalArgumentException ex) {
                    String error = ex.getLocalizedMessage();
                    JOptionPane.showMessageDialog(viewBuildings, error);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        viewBuildings = new JPanel();
        viewBuildings.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        viewBuildings.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("전체 지점 조회");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        viewBuildings.add(label1, gbc);
        BACKButton = new JButton();
        BACKButton.setText("메인 메뉴");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        viewBuildings.add(BACKButton, gbc);
        SHOWBUILDINGSButton = new JButton();
        SHOWBUILDINGSButton.setText("지점 보기");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        viewBuildings.add(SHOWBUILDINGSButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return viewBuildings;
    }

}
